apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/zy445566/helloworld-nodejs
        env:
        - name: TARGET
          value: "Node.js Sample Native v1"