[package]
name = "fib"
version = "0.1.0"
authors = ["ZY <zyct@vip.qq.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "fib"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.18"

[dependencies]
neon = "0.1.18"
